### ISSUE TITLE
Design state for "Add to profile" when no main file present

### ISSUE THREAD

**Issue by chartgerink** [hypergraph-xyz/desktop#134] opened 2020-07-01 14:12 UTC
## Description

Currently, the "Add to profile" is clickable when no main file is present in a content module. It produces an error (attached) when clicked at the moment, but we don't have a design to notify the user that they need to add a main file. 

<img width="1552" alt="Screenshot 2020-07-01 at 15 04 46" src="https://user-images.githubusercontent.com/2946344/86253973-80a51a80-bbb5-11ea-9261-3dba49c115ff.png">

## To Reproduce

1. Create a content module without main file
2. Add to profile

**Comment by psobrakseaton** [comment] 2020-07-02 09:07
Does a user NEED to add a main file, if so, I feel this should be addressed perhaps on the add content screen or if we want users to be able to add content without a file we should have the "Add to profile" button be "Add main file" instead and take them to the edit content page.

Thoughts?

**Comment by chartgerink** [comment] 2020-07-02 09:22
Upon adding to profile, a main file is required. Upon adding content to drafts, it isn't required.

I think replacing the "Add to profile" button with the action required makes sense, sort of? If we implement the "Add to profile" "Save as draft" and "Cancel" in the Add/edit content screen this will help as well.

@juliangruber what do you think from a UX perspective?

**Comment by juliangruber** [comment] 2020-07-02 09:27
If we just change the button text from "Add to profile" to "Add main file", I doubt users would notice it.

There's one or two steps necessary for the user to fix this situation:

1. If no file has been added, or if no suiting file has been added:
  1. Add one or more files
2. Choose which file to use as the main file

The new "update content module" screen should offer these capabilities, and is going to be implemented during this cycle https://github.com/hypergraph-xyz/desktop/issues/69.

How we get there I'm not sure, but I think the user should go to that screen to fix the problem.

**Comment by psobrakseaton** [comment] 2020-07-02 09:44
I think I see several possibilities for dealing with this.

p.1: After clicking "Add to profile" get taken to an add/edit content screen where the add file/main file action is a requirement. - might be simplest to implement.

p.2: Take them to a specialized form or modal for just the files. -seems design and implementation heavy.

p.2: Add back an empty files section with a button to upload files (like in the form) and disable the "Add to profile" button until those are uploaded. - also a bit design and implementation heavy, but might be the most UX obvious.

I have a question though, I have also designed scenarios where there are multiple file uploads but no "main file". If we need a main file, that will change a lot of the flow of the feature.

If you'd prefer, it might be easier to talk about this instead of writing it all out. I'll start a call in W.O.

**Comment by chartgerink** [comment] 2020-07-02 10:22
Some suggested copy for when there is no main file:

> ⚠️ Warning: You must add a main file before adding to profile

**Comment by jameslibscie** [comment] 2020-07-07 09:26
I think this is caused by an SDK update that implements this spec, as these errors weren't generated before. It makes the most sense to me to display a warning dialog when users click "Add to profile". 
- Just greying it out doesn't provide enough feedback
- Always displaying a warning is a bit too much I think
- Specialised forms / modals seems too much work
- Taking them to a modified edit content screen might be confusing as this would only happen under specific circumstances that aren't obvious

@psobrakseaton it will still be possible to have no main file, as long as the content is still a draft.

Small update to copy:
> ⚠️ Warning: You must select a main file before adding to profile

**Comment by juliangruber** [comment] 2020-07-08 09:17
In UX, it it is impossible to submit a form through some button, I would like to see why that is. I would be quite surprised if anyone clicked the grayed out button to figure out what’s wrong.

The explanation doesn’t have to be very prominent, it could be as gray as the button maybe.

**Comment by juliangruber** [comment] 2020-07-08 09:21
It probably helps if the description doesn’t start with “Warning”

**Comment by jameslibscie** [comment] 2020-07-09 12:13
Just to clarify, if we're doing a warning modal, I don't think the button should be greyed out. So it would be a green button that displays a modal when clicked.

Greyed out button with greyed out explanation could work too. Or how about greyed out button with an explanation when hovered over? Or greyed out button with an info icon that displays more info when hovered over?

**Comment by psobrakseaton** [comment] 2020-07-29 10:28
What is the status on this issue? Do we consider this resolved with the changes we created last cycle, or is there any pending decisions to be made? @jameslibscie @chartgerink @juliangruber

**Comment by jameslibscie** [comment] 2020-07-29 10:30
Already implemented :)

**Closed by jameslibscie** 2020-07-29 10:30 UTC
Labels: bug
