### ISSUE TITLE
Second instance with LOCK / IO error after having the app minimized

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/desktop#123] opened 2020-06-24 09:32 UTC
## Description

After having the app minimized for a while, then clicking the dock icon for Hypergraph, a second instance comes up displaying a LOCK / IO error. A second instance should not open.

## To Reproduce

@psobrakseaton is trying to reproduce, but the steps should be something like:
1. Minimize Hypergraph
2. Wait a long time
3. Click the dock icon

## Expected behavior

The existing instance opens

## Actual behavior

A new instance opens

## Screenshots

![image](https://user-images.githubusercontent.com/59870484/85530541-4e704780-b60e-11ea-8e82-e42f4b0bb67d.png)

## System

- OS (incl. version): macOS 10.1x
- Hypergraph Desktop version: 0.2.2

**Comment by juliangruber** [comment] 2020-09-28 08:33
I can't reproduce this, and there hasn't been another successful attempt since June, so I'm closing this one

**Closed by juliangruber** 2020-09-28 08:33 UTC
Labels: bug, mac
