### ISSUE TITLE
Delete button fails

### ISSUE THREAD

**Issue by chartgerink** [hypergraph-xyz/desktop#232] opened 2020-08-21 08:33 UTC
## Description

When I try to delete a (registered) content module, the delete method fails.

## To Reproduce

1. Download 0.6.0
2. Create draft or registered module
3. Click "Delete content" 
4. Confirm delete
5. Delete does not complete

## Expected behavior

Content module gets deleted.

## Actual behavior

Delete fails and goes back to Feed.

## Screenshots

![Screenshot 2020-08-21 at 10 29 44 (2)](https://user-images.githubusercontent.com/2946344/90870122-72939f00-e399-11ea-932d-100dff880a7a.png)

## System

- OS (incl. version): macOS 10.15.6 + Windows
- Hypergraph Desktop version: 0.6.0

## Additional context

The `@p2pcommons/sdk-js` recently introduced a  fix to also allow the deletion of versioned modules. This might have broken the current delete mechanism?

**Comment by jameslibscie** [comment] 2020-08-21 08:34
This is a duplicate of #217 and is already being looked into. The SDK update for deleting versioned modules hasn't landed in Hypergraph yet.

**Closed by jameslibscie** 2020-08-21 08:34 UTC
Labels: bug
