### ISSUE TITLE
Error when adding new module with main file - file locking by antivirus

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/desktop#63] opened 2020-04-09 10:05 UTC
__Edit__ @juliangruber: SDK issue https://github.com/p2pcommons/sdk-js/issues/173

## Description

When adding content with a main file, I get an error message "Error: EBUSY: resource busy or locked". The error displays the file path in the `.p2pcommons` directory. The module is created correctly, including the main file.

![image](https://user-images.githubusercontent.com/59870484/78882797-e53e5680-7a58-11ea-91a7-82f9a7e8ca13.png)

If I don't select a main file, I get no error (even if the module contains other files). If I add multiple files and select a main, I only get the error for the main file. It therefore seems like the error is related specifically to the main file.

## To Reproduce

1. Click 'Add content'
2. Choose at least one file
3. Select a main file
4. Add the content
5. Error pops up

## Desktop

- OS: Windows 10
- Version: [https://github.com/hypergraph-xyz/desktop/runs/568083152](build 980c0b5)

**Comment by jameslibscie** [comment] 2020-04-09 10:15
This seems to be related to Bitdefender. After disabling, I no longer get this error. After re-enabling and restarting Hypergraph, the error reoccurs.

**Comment by juliangruber** [comment] 2020-04-09 13:05
Idea: retry fs operations after they fail this way

**Comment by juliangruber** [comment] 2020-04-09 13:05
> EBUSY can bubble up if a file is temporarily locked in windows (for example during AV scan or Dropbox sync)

https://github.com/isaacs/node-graceful-fs/issues/127

**Comment by jameslibscie** [comment] 2020-05-06 15:08
I've seen this happen with a test user using FSecure as well btw, so it's not just Bitdefender

**Comment by juliangruber** [comment] 2020-06-25 14:10
Hypergraph currently doesn't work in my Windows VM, due to some native module issues. I tried upgrading Electron and other deps but am blocked by https://github.com/p2pcommons/sdk-js/issues/165.

**Comment by juliangruber** [comment] 2020-06-25 14:11
In the meantime I've sent James patch suggestions (since he can reproduce locally) via Slack, which we're going to try this way

**Comment by juliangruber** [comment] 2020-06-30 08:31
This error isn't catchable directly from the `sdk` calls Desktop makes. It needs to be exposed or fixed in the SDK, _or_ we can tune the global `onerror` handler to simply ignore it.

**Comment by juliangruber** [comment] 2020-06-30 08:31
@jameslibscie did you talk to @dpaez about this?

**Comment by dpaez** [comment] 2020-06-30 19:37
@juliangruber don't remember talking about this with james. But we can deal with this in the SDK as you suggest julian.

**Comment by juliangruber** [comment] 2020-07-02 07:19
SDK issue: https://github.com/p2pcommons/sdk-js/issues/173

**Closed** 2020-07-14 10:47 UTC
Labels: bug, windows
