### ISSUE TITLE
Handle disallowed main file extensions

### ISSUE THREAD

**Issue by jameslibscie** [hypergraph-xyz/desktop#249] opened 2020-08-31 14:05 UTC
The SDK now only allows certain open file extensions for the main file. If the user has a disallowed file type as the main file, the error is not yet handled by Hypergraph.

EDIT: The user should be encouraged to use the chat if they think something is incorrectly being disallowed.

**Comment by juliangruber** [comment] 2020-09-15 21:20
See https://github.com/hypergraph-xyz/desktop/pull/269#issuecomment-692765321 for design consideration

**Comment by psobrakseaton** [comment] 2020-09-21 12:27
Discussed over in #269. I will unassign myself here. Should this issue be closed instead?

**Comment by juliangruber** [comment] 2020-09-21 13:40
This hasn't been solved yet, Patch. Shall we sync in person?

**Comment by psobrakseaton** [comment] 2020-09-22 11:04
What should I do in a situation like this where the issue is discussed and decided somewhere else (#269)?

Should I close this? Reassign it? Just leave it? 

Curious what the proper GitHub etiquette is for this...

**Comment by juliangruber** [comment] 2020-09-22 11:07
You most of the time have an issue and a pull request, that are linked. The issue is assigned to the person that needs to do the work and will only be closed once the pull request is closed. We can assign this issue to me now, since design is done.

**Closed** 2020-09-23 07:39 UTC
Labels: bug, design, feature
